ホットリロード対応
babyhotate/buri pull request #26
Opened 2021-03-02 10:42 UTC by nananakano000

npm startでホットリロード起動できるように対応しました。

2021-03-06 16:42 UTC, aksh-t requested changes
コメントしました。
明日のモブの時にみんなで一緒に見ましょう。

2021-03-06 16:42 UTC, aksh-t commented on package.json
> +    "start": "nodemon -e ejs,js,json start ./bin/www"
オプションおよび引数( `-e ejs,js,json start ./bin/www` )はなくて大丈夫そうです

2021-03-06 16:42 UTC, aksh-t commented on package.json
> +    "nodemon": "^2.0.7"
[IMO]
仮にこのアプリを本番環境で動かす際、nodemonは使わないような気がしています。
ので、 `dependencies` じゃなくて `devDependencies` にインストールした方がいいと思いました。

2021-03-06 16:42 UTC, aksh-t commented on package.json
> +    "nodemon": "^2.0.7"
と思ったけど、そうすると `start` スクリプトも工夫が必要なのでこのままの方がいいのかな...。
（nodemon入れてる他のプロジェクトはどうしてるんだろう🤔）

2021-03-07 02:57 UTC, nananakano000 commented
コメントありがとうございます！
モブの時に修正します

2021-03-07 06:06 UTC, aksh-t approved these changes
LGTM

2021-03-07 06:07 UTC, merged

2021-03-07 08:03 UTC, aksh-t commented
ちなみに