ポストを追加するAPI追加
babyhotate/buri pull request #88
Opened 2021-09-26 05:04 UTC by shellzu

- APIを追加
- 入力値が不正な場合はpostを登録せずに400を返す

2021-09-27 16:33 UTC, aksh-t requested changes
コメントしました。
何点か修正お願いします。

2021-10-17 06:37 UTC, shellzu commented on app.js
> +    res.status(200);
res.status(200);を削除します。

2021-10-17 06:37 UTC, shellzu commented on app.js
> +  if (req.query.user && req.query.post) {
bodyで受け取るように修正します。

2021-10-17 06:37 UTC, shellzu commented on app.js
> +  } else {
早期リターンするように修正します。

2021-10-17 06:39 UTC, shellzu commented on app.js
> +  });
prittierを再読み込みして、VScodeの再起動をし、フォーマットを修正します。

2021-10-17 06:41 UTC, aksh-t commented
test
1e85b651aef6d5d5a598deef782df7cf7e1eb949

2021-10-17 06:49 UTC, aksh-t approved these changes
![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F594950cc-39d2-4e69-99ff-88729c0bb2b2.jpg?alt=media&token=617aab40-756f-4c9b-af85-616915b4d788)

2021-10-17 06:52 UTC, shellzu commented
aksh-tがapprovedしたのでマージします。

2021-10-17 07:17 UTC, merged